<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_CURA_Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>a6554ee5-8a01-4e56-9f3d-218aaa361c81</testSuiteGuid>
   <testCaseLink>
      <guid>c2965d53-1268-4911-9653-d2ecdacb97e8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CURA_UserAthentication/TC_CURA_Login_001</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>601dd809-d03a-48c9-95f7-cbf2da19f2b4</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Test Data_CURA_ExcellSheet_Login/DD_Login_TestData_3</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>601dd809-d03a-48c9-95f7-cbf2da19f2b4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>37b9ae43-48fd-48ca-b75b-5e63e2df7346</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>601dd809-d03a-48c9-95f7-cbf2da19f2b4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>4034deee-fb5d-44a8-844d-25abd887e4a1</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
